## Naive Bayes

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Social_Network_Ads.csv')
data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
# remove userID column
data = data.drop('User ID', axis= 1)
data.head()

   Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [4]:
X = data.iloc[:, :-1].values
Y = data.iloc[:, -1].values

print(X.shape)
print(Y.shape)

(400, 3)
(400,)

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=0)

print(X_train.shape)
print(X_test.shape)

(320, 3)
(80, 3)

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

CT = ColumnTransformer(
    transformers = [
        ('encoder', OneHotEncoder(drop='first', sparse=False), [0]),
        ('scaler', StandardScaler(), [1,2])
    ]
)

In [7]:
# Fit it in X_train and transform both X_train and X_test
X_train = CT.fit_transform(X_train)
X_test = CT.transform(X_test)

c:\Users\gusai\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [8]:
print(X_train)

[[ 1.00000000e+00  1.92295008e+00  2.14601566e+00]
 [ 0.00000000e+00  2.02016082e+00  3.78719297e-01]
 [ 0.00000000e+00 -1.38221530e+00 -4.32498705e-01]
 [ 0.00000000e+00 -1.18779381e+00 -1.01194013e+00]
 [ 0.00000000e+00  1.92295008e+00 -9.25023920e-01]
 [ 0.00000000e+00  3.67578135e-01  2.91803083e-01]
 [ 0.00000000e+00  1.73156642e-01  1.46942725e-01]
 [ 1.00000000e+00  2.02016082e+00  1.74040666e+00]
 [ 0.00000000e+00  7.56421121e-01 -8.38107706e-01]
 [ 0.00000000e+00  2.70367388e-01 -2.87638347e-01]
 [ 1.00000000e+00  3.67578135e-01 -1.71750061e-01]
 [ 0.00000000e+00 -1.18475597e-01  2.20395980e+00]
 [ 0.00000000e+00 -1.47942605e+00 -6.35303205e-01]
 [ 1.00000000e+00 -1.28500455e+00 -1.06988428e+00]
 [ 1.00000000e+00 -1.38221530e+00  4.07691369e-01]
 [ 0.00000000e+00 -1.09058306e+00  7.55356227e-01]
 [ 1.00000000e+00 -1.47942605e+00 -2.00722133e-01]
 [ 1.00000000e+00  9.50842613e-01 -1.06988428e+00]
 [ 1.00000000e+00  9.50842613e-01  5.81523798e-01]
 [ 1.00000000e+00  3.67578135e-01  9.87132798e-01]
 [ 0.00000000e+00  5.61999628e-01 -8.96051849e-01]
 [ 1.00000000e+00 -6.04529329e-01  1.45068594e+00]
 [ 0.00000000e+00 -2.12648508e-02 -5.77359062e-01]
 [ 0.00000000e+00 -6.04529329e-01  1.88526701e+00]
 [ 0.00000000e+00  1.33968560e+00 -1.41754914e+00]
 [ 0.00000000e+00  1.43689635e+00  9.87132798e-01]
 [ 1.00000000e+00  7.59458956e-02 -8.09135634e-01]
 [ 1.00000000e+00 -2.12648508e-02 -2.58666276e-01]
 [ 0.00000000e+00 -2.15686344e-01 -5.77359062e-01]
 [ 0.00000000e+00 -2.15686344e-01 -2.00722133e-01]
 [ 0.00000000e+00 -3.12897090e-01 -1.30166085e+00]
 [ 1.00000000e+00 -3.12897090e-01 -5.77359062e-01]
 [ 1.00000000e+00  3.67578135e-01  8.89985821e-02]
 [ 0.00000000e+00  8.53631867e-01 -6.06331134e-01]
 [ 0.00000000e+00  2.02016082e+00 -1.18577256e+00]
 [ 1.00000000e+00  1.04805336e+00 -1.42777990e-01]
 [ 0.00000000e+00  6.59210374e-01  1.76937873e+00]
 [ 0.00000000e+00 -7.01740076e-01  5.52551726e-01]
 [ 0.00000000e+00  7.56421121e-01  3.49747226e-01]
 [ 0.00000000e+00  8.53631867e-01 -5.48386991e-01]
 [ 1.00000000e+00 -1.18779381e+00 -1.59138156e+00]
 [ 1.00000000e+00  2.11737157e+00  9.29188655e-01]
 [ 0.00000000e+00 -2.12648508e-02  1.21890937e+00]
 [ 1.00000000e+00  1.73156642e-01  1.07404901e+00]
 [ 0.00000000e+00  3.67578135e-01 -4.90442848e-01]
 [ 1.00000000e+00 -3.12897090e-01 -3.16610419e-01]
 [ 1.00000000e+00  9.50842613e-01 -8.38107706e-01]
 [ 0.00000000e+00  9.50842613e-01  1.85629494e+00]
 [ 0.00000000e+00 -2.12648508e-02  1.24788144e+00]
 [ 1.00000000e+00 -8.96161568e-01  2.26190394e+00]
 [ 0.00000000e+00 -1.18779381e+00 -1.59138156e+00]
 [ 1.00000000e+00  2.11737157e+00 -8.09135634e-01]
 [ 1.00000000e+00 -1.38221530e+00 -1.47549328e+00]
 [ 1.00000000e+00  3.67578135e-01  2.29087602e+00]
 [ 0.00000000e+00  7.56421121e-01  7.55356227e-01]
 [ 1.00000000e+00 -9.93372315e-01 -3.16610419e-01]
 [ 1.00000000e+00  7.59458956e-02  7.55356227e-01]
 [ 1.00000000e+00 -9.93372315e-01  5.52551726e-01]
 [ 1.00000000e+00  2.70367388e-01  6.00265106e-02]
 [ 1.00000000e+00  6.59210374e-01 -1.27268878e+00]
 [ 0.00000000e+00 -5.07318583e-01 -2.68897039e-02]
 [ 0.00000000e+00 -1.77105829e+00  3.49747226e-01]
 [ 1.00000000e+00 -7.01740076e-01  1.17970654e-01]
 [ 1.00000000e+00  3.67578135e-01  2.91803083e-01]
 [ 0.00000000e+00 -3.12897090e-01  6.00265106e-02]
 [ 0.00000000e+00 -5.07318583e-01  2.29087602e+00]
 [ 1.00000000e+00  1.73156642e-01  3.10544391e-02]
 [ 0.00000000e+00  1.24247485e+00  2.20395980e+00]
 [ 1.00000000e+00  7.56421121e-01  2.62831011e-01]
 [ 1.00000000e+00 -3.12897090e-01  1.46942725e-01]
 [ 1.00000000e+00 -2.12648508e-02 -5.48386991e-01]
 [ 0.00000000e+00 -2.15686344e-01  1.46942725e-01]
 [ 0.00000000e+00 -1.18475597e-01  2.33858940e-01]
 [ 1.00000000e+00 -2.12648508e-02 -2.58666276e-01]
 [ 0.00000000e+00  2.11737157e+00  1.10302108e+00]
 [ 0.00000000e+00 -1.77105829e+00  3.49747226e-01]
 [ 1.00000000e+00  1.82573933e+00  1.17970654e-01]
 [ 1.00000000e+00  3.67578135e-01 -1.42777990e-01]
 [ 1.00000000e+00 -1.18779381e+00  2.91803083e-01]
 [ 1.00000000e+00  7.56421121e-01  1.36376973e+00]
 [ 1.00000000e+00 -3.12897090e-01 -2.58666276e-01]
 [ 0.00000000e+00 -1.67384754e+00 -5.58617754e-02]
 [ 0.00000000e+00 -9.93372315e-01 -7.51191491e-01]
 [ 1.00000000e+00  2.70367388e-01  4.94607583e-01]
 [ 0.00000000e+00 -1.18475597e-01 -1.06988428e+00]
 [ 1.00000000e+00 -1.09058306e+00  5.81523798e-01]
 [ 1.00000000e+00  7.59458956e-02 -8.09135634e-01]
 [ 1.00000000e+00 -9.93372315e-01  1.53760216e+00]
 [ 0.00000000e+00 -7.01740076e-01  1.39274180e+00]
 [ 1.00000000e+00 -1.28500455e+00  4.94607583e-01]
 [ 0.00000000e+00 -3.12897090e-01  3.10544391e-02]
 [ 1.00000000e+00 -1.18475597e-01  2.08236764e-03]
 [ 1.00000000e+00 -3.12897090e-01 -8.96051849e-01]
 [ 1.00000000e+00  8.53631867e-01 -1.35960499e+00]
 [ 0.00000000e+00 -3.12897090e-01  2.23293187e+00]
 [ 0.00000000e+00  9.50842613e-01  1.97218323e+00]
 [ 1.00000000e+00 -1.18779381e+00  4.65635512e-01]
 [ 1.00000000e+00 -1.28500455e+00  2.62831011e-01]
 [ 0.00000000e+00  1.33968560e+00  1.97218323e+00]
 [ 1.00000000e+00  1.24247485e+00 -1.35960499e+00]
 [ 0.00000000e+00 -3.12897090e-01 -2.87638347e-01]
 [ 0.00000000e+00 -5.07318583e-01  1.24788144e+00]
 [ 1.00000000e+00 -7.98950822e-01  1.07404901e+00]
 [ 1.00000000e+00  9.50842613e-01 -1.06988428e+00]
 [ 0.00000000e+00  2.70367388e-01  2.91803083e-01]
 [ 0.00000000e+00  9.50842613e-01  7.55356227e-01]
 [ 1.00000000e+00 -7.01740076e-01 -1.50446535e+00]
 [ 0.00000000e+00 -7.01740076e-01  3.10544391e-02]
 [ 1.00000000e+00  4.64788881e-01  1.71143459e+00]
 [ 0.00000000e+00  2.02016082e+00  1.75914797e-01]
 [ 0.00000000e+00 -1.96547978e+00 -7.51191491e-01]
 [ 1.00000000e+00 -2.15686344e-01  1.39274180e+00]
 [ 0.00000000e+00  3.67578135e-01  5.81523798e-01]
 [ 0.00000000e+00  8.53631867e-01 -1.15680049e+00]
 [ 0.00000000e+00 -1.18779381e+00 -7.80163563e-01]
 [ 1.00000000e+00  1.73156642e-01  2.33858940e-01]
 [ 1.00000000e+00  7.56421121e-01 -3.16610419e-01]
 [ 0.00000000e+00  2.02016082e+00 -8.09135634e-01]
 [ 0.00000000e+00  7.56421121e-01  1.17970654e-01]
 [ 1.00000000e+00 -3.12897090e-01  6.10495869e-01]
 [ 0.00000000e+00 -9.93372315e-01 -3.16610419e-01]
 [ 1.00000000e+00  1.73156642e-01 -3.74554562e-01]
 [ 1.00000000e+00  2.02016082e+00  2.11704359e+00]
 [ 0.00000000e+00  1.82573933e+00 -1.27268878e+00]
 [ 0.00000000e+00  1.33968560e+00 -9.25023920e-01]
 [ 0.00000000e+00  8.53631867e-01  1.24788144e+00]
 [ 0.00000000e+00  1.43689635e+00  2.11704359e+00]
 [ 1.00000000e+00 -3.12897090e-01 -1.24371671e+00]
 [ 0.00000000e+00  1.92295008e+00  9.00216584e-01]
 [ 0.00000000e+00  6.59210374e-01 -7.22219420e-01]
 [ 0.00000000e+00 -1.47942605e+00  3.49747226e-01]
 [ 1.00000000e+00  7.56421121e-01 -1.35960499e+00]
 [ 1.00000000e+00  3.67578135e-01 -1.42777990e-01]
 [ 0.00000000e+00 -9.93372315e-01  4.07691369e-01]
 [ 1.00000000e+00 -2.12648508e-02 -3.16610419e-01]
 [ 0.00000000e+00 -1.18779381e+00  4.07691369e-01]
 [ 0.00000000e+00 -8.96161568e-01 -1.21474464e+00]
 [ 0.00000000e+00 -1.18475597e-01  3.10544391e-02]
 [ 0.00000000e+00 -1.57663679e+00 -4.32498705e-01]
 [ 0.00000000e+00  9.50842613e-01 -1.01194013e+00]
 [ 1.00000000e+00  1.04805336e+00 -1.21474464e+00]
 [ 0.00000000e+00 -2.12648508e-02 -1.42777990e-01]
 [ 0.00000000e+00 -1.09058306e+00 -1.53343742e+00]
 [ 1.00000000e+00  7.56421121e-01 -1.21474464e+00]
 [ 1.00000000e+00  9.50842613e-01  2.05909944e+00]
 [ 0.00000000e+00 -1.18779381e+00 -1.53343742e+00]
 [ 0.00000000e+00 -3.12897090e-01  7.84328298e-01]
 [ 0.00000000e+00  7.59458956e-02 -3.16610419e-01]
 [ 0.00000000e+00 -1.38221530e+00 -1.24371671e+00]
 [ 1.00000000e+00 -6.04529329e-01 -1.50446535e+00]
 [ 1.00000000e+00  7.56421121e-01  5.23579655e-01]
 [ 1.00000000e+00 -3.12897090e-01 -3.45582490e-01]
 [ 1.00000000e+00  1.72852858e+00 -2.87638347e-01]
 [ 1.00000000e+00  8.53631867e-01 -1.04091221e+00]
 [ 0.00000000e+00  1.73156642e-01  6.00265106e-02]
 [ 1.00000000e+00 -6.04529329e-01  8.71244512e-01]
 [ 0.00000000e+00 -1.86826903e+00 -1.41754914e+00]
 [ 1.00000000e+00 -1.28500455e+00  5.81523798e-01]
 [ 1.00000000e+00 -3.12897090e-01  5.23579655e-01]
 [ 1.00000000e+00 -9.93372315e-01 -1.09885635e+00]
 [ 0.00000000e+00  1.14526411e+00 -1.44652121e+00]
 [ 1.00000000e+00  1.73156642e-01 -3.16610419e-01]
 [ 0.00000000e+00  1.14526411e+00 -7.51191491e-01]
 [ 1.00000000e+00 -3.12897090e-01  6.00265106e-02]
 [ 0.00000000e+00  1.73156642e-01  2.08807152e+00]
 [ 0.00000000e+00  7.56421121e-01 -1.09885635e+00]
 [ 0.00000000e+00  7.59458956e-02  3.10544391e-02]
 [ 1.00000000e+00 -1.77105829e+00  1.17970654e-01]
 [ 1.00000000e+00 -8.96161568e-01  1.46942725e-01]
 [ 1.00000000e+00 -7.01740076e-01  1.75914797e-01]
 [ 1.00000000e+00  8.53631867e-01 -1.30166085e+00]
 [ 1.00000000e+00  1.73156642e-01 -2.58666276e-01]
 [ 1.00000000e+00 -4.10107836e-01  1.21890937e+00]
 [ 0.00000000e+00 -2.12648508e-02  2.91803083e-01]
 [ 0.00000000e+00  3.67578135e-01  1.46942725e-01]
 [ 0.00000000e+00  8.53631867e-01 -6.64275277e-01]
 [ 0.00000000e+00  7.59458956e-02  1.46942725e-01]
 [ 1.00000000e+00 -1.86826903e+00 -1.30166085e+00]
 [ 0.00000000e+00 -1.18475597e-01  2.91803083e-01]
 [ 1.00000000e+00 -2.15686344e-01 -2.87638347e-01]
 [ 1.00000000e+00  2.70367388e-01 -5.19414919e-01]
 [ 1.00000000e+00 -2.15686344e-01  1.59554630e+00]
 [ 0.00000000e+00  9.50842613e-01 -1.18577256e+00]
 [ 0.00000000e+00 -2.15686344e-01  1.62451837e+00]
 [ 0.00000000e+00  1.24247485e+00  1.85629494e+00]
 [ 0.00000000e+00 -1.09058306e+00 -3.74554562e-01]
 [ 1.00000000e+00 -2.12648508e-02  3.10544391e-02]
 [ 0.00000000e+00  7.59458956e-02 -2.58666276e-01]
 [ 0.00000000e+00 -1.57663679e+00 -1.24371671e+00]
 [ 0.00000000e+00 -5.07318583e-01 -2.87638347e-01]
 [ 1.00000000e+00  9.50842613e-01  1.17970654e-01]
 [ 0.00000000e+00  1.92295008e+00 -1.35960499e+00]
 [ 1.00000000e+00  1.43689635e+00  6.00265106e-02]
 [ 0.00000000e+00 -6.04529329e-01  1.36376973e+00]
 [ 1.00000000e+00  1.53410709e+00  2.08236764e-03]
 [ 1.00000000e+00 -7.98950822e-01  2.91803083e-01]
 [ 0.00000000e+00  1.92295008e+00  7.26384155e-01]
 [ 0.00000000e+00 -1.18779381e+00 -5.19414919e-01]
 [ 1.00000000e+00  6.59210374e-01  2.62831011e-01]
 [ 1.00000000e+00 -1.38221530e+00 -4.32498705e-01]
 [ 1.00000000e+00  1.73156642e-01  1.46942725e-01]
 [ 0.00000000e+00 -5.07318583e-01 -1.21474464e+00]
 [ 0.00000000e+00  5.61999628e-01  2.00115530e+00]
 [ 1.00000000e+00 -1.57663679e+00 -1.50446535e+00]
 [ 0.00000000e+00 -5.07318583e-01 -5.48386991e-01]
 [ 0.00000000e+00  4.64788881e-01  1.82732287e+00]
 [ 0.00000000e+00 -1.38221530e+00 -1.09885635e+00]
 [ 0.00000000e+00  7.56421121e-01 -1.38857706e+00]
 [ 1.00000000e+00 -3.12897090e-01 -4.32498705e-01]
 [ 0.00000000e+00  1.53410709e+00  9.87132798e-01]
 [ 0.00000000e+00  9.50842613e-01  1.42171387e+00]
 [ 1.00000000e+00 -3.12897090e-01 -4.90442848e-01]
 [ 1.00000000e+00 -1.18475597e-01  2.14601566e+00]
 [ 0.00000000e+00 -1.47942605e+00 -1.13805918e-01]
 [ 0.00000000e+00 -1.18475597e-01  1.94321116e+00]
 [ 1.00000000e+00 -7.01740076e-01 -3.45582490e-01]
 [ 0.00000000e+00 -5.07318583e-01 -8.38107706e-01]
 [ 0.00000000e+00  6.59210374e-01 -1.38857706e+00]
 [ 1.00000000e+00 -7.98950822e-01 -1.59138156e+00]
 [ 1.00000000e+00 -1.86826903e+00 -1.47549328e+00]
 [ 1.00000000e+00  1.04805336e+00  1.17970654e-01]
 [ 1.00000000e+00  7.59458956e-02  1.50863009e+00]
 [ 1.00000000e+00 -3.12897090e-01  8.89985821e-02]
 [ 1.00000000e+00  7.59458956e-02  3.10544391e-02]
 [ 1.00000000e+00 -1.38221530e+00 -1.35960499e+00]
 [ 0.00000000e+00  2.70367388e-01  6.00265106e-02]
 [ 0.00000000e+00 -8.96161568e-01  3.78719297e-01]
 [ 0.00000000e+00  1.53410709e+00 -1.27268878e+00]
 [ 0.00000000e+00 -3.12897090e-01 -7.51191491e-01]
 [ 1.00000000e+00 -1.18475597e-01  1.46942725e-01]
 [ 0.00000000e+00 -8.96161568e-01 -6.64275277e-01]
 [ 0.00000000e+00 -7.01740076e-01 -5.58617754e-02]
 [ 1.00000000e+00  3.67578135e-01 -4.61470776e-01]
 [ 1.00000000e+00 -7.98950822e-01  1.88526701e+00]
 [ 0.00000000e+00  1.33968560e+00  1.27685351e+00]
 [ 0.00000000e+00  1.14526411e+00 -9.82968063e-01]
 [ 1.00000000e+00  1.72852858e+00  1.82732287e+00]
 [ 1.00000000e+00 -8.96161568e-01 -2.58666276e-01]
 [ 1.00000000e+00 -7.98950822e-01  5.52551726e-01]
 [ 1.00000000e+00 -1.18779381e+00 -1.56240949e+00]
 [ 1.00000000e+00 -5.07318583e-01 -1.12782842e+00]
 [ 0.00000000e+00  2.70367388e-01  6.00265106e-02]
 [ 1.00000000e+00 -2.15686344e-01 -1.06988428e+00]
 [ 0.00000000e+00  1.63131784e+00  1.59554630e+00]
 [ 0.00000000e+00  9.50842613e-01  1.76937873e+00]
 [ 0.00000000e+00  2.70367388e-01  3.10544391e-02]
 [ 0.00000000e+00 -7.98950822e-01 -2.29694204e-01]
 [ 1.00000000e+00 -1.18475597e-01  6.00265106e-02]
 [ 0.00000000e+00  2.70367388e-01 -2.00722133e-01]
 [ 0.00000000e+00  1.92295008e+00 -6.64275277e-01]
 [ 0.00000000e+00 -7.98950822e-01  1.33479766e+00]
 [ 1.00000000e+00 -1.77105829e+00 -6.06331134e-01]
 [ 1.00000000e+00 -1.18475597e-01  1.17970654e-01]
 [ 1.00000000e+00  2.70367388e-01 -3.16610419e-01]
 [ 1.00000000e+00  1.04805336e+00  5.52551726e-01]
 [ 1.00000000e+00 -9.93372315e-01  2.62831011e-01]
 [ 0.00000000e+00  1.43689635e+00  3.49747226e-01]
 [ 1.00000000e+00  1.73156642e-01 -3.74554562e-01]
 [ 1.00000000e+00  2.11737157e+00 -1.04091221e+00]
 [ 1.00000000e+00 -3.12897090e-01  1.10302108e+00]
 [ 1.00000000e+00 -1.67384754e+00  6.00265106e-02]
 [ 1.00000000e+00 -2.12648508e-02  3.10544391e-02]
 [ 1.00000000e+00  7.59458956e-02  1.04507694e+00]
 [ 0.00000000e+00 -1.18475597e-01 -3.74554562e-01]
 [ 0.00000000e+00 -1.18779381e+00  6.00265106e-02]
 [ 0.00000000e+00 -3.12897090e-01 -1.35960499e+00]
 [ 0.00000000e+00  1.53410709e+00  1.10302108e+00]
 [ 1.00000000e+00 -7.98950822e-01 -1.53343742e+00]
 [ 1.00000000e+00  7.59458956e-02  1.85629494e+00]
 [ 1.00000000e+00 -8.96161568e-01 -7.80163563e-01]
 [ 1.00000000e+00 -5.07318583e-01 -7.80163563e-01]
 [ 1.00000000e+00 -3.12897090e-01 -9.25023920e-01]
 [ 1.00000000e+00  2.70367388e-01 -7.22219420e-01]
 [ 0.00000000e+00  2.70367388e-01  6.00265106e-02]
 [ 0.00000000e+00  7.59458956e-02  1.85629494e+00]
 [ 0.00000000e+00 -1.09058306e+00  1.94321116e+00]
 [ 0.00000000e+00 -1.67384754e+00 -1.56240949e+00]
 [ 1.00000000e+00 -1.18779381e+00 -1.09885635e+00]
 [ 1.00000000e+00 -7.01740076e-01 -1.13805918e-01]
 [ 0.00000000e+00  7.59458956e-02  8.89985821e-02]
 [ 1.00000000e+00  2.70367388e-01  2.62831011e-01]
 [ 0.00000000e+00  8.53631867e-01 -5.77359062e-01]
 [ 0.00000000e+00  2.70367388e-01 -1.15680049e+00]
 [ 0.00000000e+00 -1.18475597e-01  6.68440012e-01]
 [ 0.00000000e+00  2.11737157e+00 -6.93247348e-01]
 [ 1.00000000e+00 -1.28500455e+00 -1.38857706e+00]
 [ 0.00000000e+00 -9.93372315e-01 -9.53995992e-01]
 [ 0.00000000e+00 -2.12648508e-02 -4.32498705e-01]
 [ 0.00000000e+00 -2.15686344e-01 -4.61470776e-01]
 [ 0.00000000e+00 -1.77105829e+00 -9.82968063e-01]
 [ 0.00000000e+00  1.72852858e+00  9.87132798e-01]
 [ 1.00000000e+00  1.73156642e-01 -3.74554562e-01]
 [ 0.00000000e+00  3.67578135e-01  1.10302108e+00]
 [ 0.00000000e+00 -1.77105829e+00 -1.35960499e+00]
 [ 1.00000000e+00  1.73156642e-01 -1.42777990e-01]
 [ 1.00000000e+00  8.53631867e-01 -1.44652121e+00]
 [ 0.00000000e+00 -1.96547978e+00  4.65635512e-01]
 [ 1.00000000e+00 -3.12897090e-01  2.62831011e-01]
 [ 0.00000000e+00  1.82573933e+00 -1.06988428e+00]
 [ 0.00000000e+00 -4.10107836e-01  6.00265106e-02]
 [ 0.00000000e+00  1.04805336e+00 -8.96051849e-01]
 [ 0.00000000e+00 -1.09058306e+00 -1.12782842e+00]
 [ 1.00000000e+00 -1.86826903e+00  2.08236764e-03]
 [ 0.00000000e+00  7.59458956e-02  2.62831011e-01]
 [ 1.00000000e+00 -1.18779381e+00  3.20775154e-01]
 [ 1.00000000e+00 -1.28500455e+00  2.91803083e-01]
 [ 0.00000000e+00 -9.93372315e-01  4.36663440e-01]
 [ 1.00000000e+00  1.63131784e+00 -8.96051849e-01]
 [ 0.00000000e+00  1.14526411e+00  5.23579655e-01]
 [ 1.00000000e+00  1.04805336e+00  5.23579655e-01]
 [ 1.00000000e+00  1.33968560e+00  2.31984809e+00]
 [ 0.00000000e+00 -3.12897090e-01 -1.42777990e-01]
 [ 1.00000000e+00  3.67578135e-01 -4.61470776e-01]
 [ 1.00000000e+00 -4.10107836e-01 -7.80163563e-01]
 [ 1.00000000e+00 -1.18475597e-01 -5.19414919e-01]
 [ 0.00000000e+00  9.50842613e-01 -1.15680049e+00]
 [ 1.00000000e+00 -8.96161568e-01 -7.80163563e-01]
 [ 1.00000000e+00 -2.15686344e-01 -5.19414919e-01]
 [ 0.00000000e+00 -1.09058306e+00 -4.61470776e-01]
 [ 0.00000000e+00 -1.18779381e+00  1.39274180e+00]]

### Train Naive Bayes

In [9]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

In [10]:
classifier.fit(X_train, Y_train)

GaussianNB()

In [11]:
y_pred = classifier.predict(X_test)

In [12]:
result = np.concatenate(
    (y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test), 1)),
    axis = 1
)

In [13]:
result

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1]], dtype=int64)

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
print('Confusion matrix\n',confusion_matrix(Y_test, y_pred))
print('\nAccuracy Score\n',accuracy_score(Y_test, y_pred))

Confusion matrix
 [[56  2]
 [ 4 18]]

Accuracy Score
 0.925